### ISSUE TITLE
base_url exception

### ISSUE THREAD

**Issue by aftabnaveed** [MageTest/BehatMage#87]
When I try to execute bin/behat it get this exception, I do have the base_url configured in my behat.yml file.

  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  Unrecognized option "base_url" under "testwork.magento"               

Am I missing something there?

**Comment by aftabnaveed** [comment]
I think to have figured it out myself. Behat3 behat.yml  might need to look like this .

``` yml
default:
    suites:
        default:
            formatter:
                name: progress
            contexts: [FeatureContext, AdminUserContext]
    extensions:
        MageTest\MagentoExtension\Extension: ~
        Behat\MinkExtension:
            base_url: "http://somesite.local"
            goutte:
                server_parameters: ~
```
